name: .NET CI with SSH Tunnel

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$(ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_NETWORK_IP }})" >> ~/.ssh/known_hosts
      
    - name: SSH Tunnel
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_NETWORK_IP: ${{ secrets.SSH_NETWORK_IP }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_PORT2: ${{ secrets.DB_PORT2 }}
        DB_HOST: ${{ secrets.DB_HOST }}
        
    - name: Start SSH agent
      run: |
        eval $(ssh-agent -s)
        
    - name: Add SSH key to SSH agent   
      run: | 
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

        # Create an SSH tunnel for MySQL
        ssh -f -N -L ${DB_PORT2}:${DB_HOST}:${DB_PORT} ${SSH_USERNAME}@${SSH_NETWORK_IP} -p ${SSH_PORT}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

#    - name: Run tests
#      env:
#        DB_HOST: $DB_HOST
#        DB_PORT: $DB_PORT2  // Local forwarded port
#        # Add other required environment variables for the database connection string
#      run: dotnet test --no-build --verbosity normal

    # Any additional steps like migrations or deployment can be added here
